Models/Aluno.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaEscolar.Models;

public class Aluno
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    
    [Required(ErrorMessage = "Por favor, digite o nome do Aluno")]
    public string Nome { get; set; }
    
    [Required(ErrorMessage = "Por favor, digite o RA do aluno")]
    [MaxLength(5)]
    public string RA { get; set; }
    
    [Required(ErrorMessage = "Por favor, digite o email do Aluno")]
    public string Email { get; set; }
    
}

Models/Conexao.cs
using Microsoft.EntityFrameworkCore;
using SistemaEscolar.Models;

namespace SistemaEscolar.DataBase;

public class Conexao : DbContext
{
    public Conexao(DbContextOptions<Conexao> options) : base(options)
    {
        
    }
    
    public DbSet<Professor> Professor { get; set; }
    
    public DbSet<Aluno> Aluno { get; set; }
}

Models/ErrorViewModel.cs
namespace SistemaEscolar.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Professor.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaEscolar.Models;

public class Professor
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    
    [Required(ErrorMessage = "Por favor, digite o nome do Professor")]
    public string Nome { get; set; }
    
    [Required(ErrorMessage = "Por favor, digite o email do Professor")]
    public string Email { get; set; }
    
    [Required(ErrorMessage = "Por favor, digite o telefone do Professor")]
    public string Telefone { get; set; }
    
    [Required(ErrorMessage = "Por favor, digite a disciplina do Professor")]
    public string Disciplina { get; set; }
}

Controllers/AlunoController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaEscolar.Interfaces;
using SistemaEscolar.Models;

namespace SistemaEscolar.Controllers;

public class AlunoController : Controller
{
    private readonly IAlunoRepository _repository;

    public AlunoController(IAlunoRepository repository)
    {
        _repository = repository;
    }
    
    [HttpGet]
    public IActionResult Adicionar()
    {
        return View((new Aluno()));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Adicionar(Aluno aluno)
    {
        if (ModelState.IsValid)
        {
            if (aluno.Id > 0)
            {
                await _repository.Atualizar(aluno);
                return RedirectToAction("Listar");
            }
            await _repository.Adicionar(aluno);
            return RedirectToAction("Listar");
        }
        return View("Adicionar", aluno);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Atualizar(int id)
    {
        var aluno = await _repository.GetById(id);
        return View("Adicionar", aluno);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Remover(int id)
    {
        await _repository.Remover(id);
        return RedirectToAction("Listar");
    }

    public async Task<IActionResult> Listar()
    {
        var alunos = await _repository.Listar();
        return View(alunos);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SistemaEscolar.Models;

namespace SistemaEscolar.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProfessorController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaEscolar.Interfaces;
using SistemaEscolar.Models;

namespace SistemaEscolar.Controllers;

public class ProfessorController : Controller
{
    private readonly IProfessorRepository _repository;

    public ProfessorController(IProfessorRepository repository)
    {
        _repository = repository;
    }
    
    [HttpGet]
    public IActionResult Adicionar()
    {
        return View((new Professor()));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Adicionar(Professor professor)
    {
        if (ModelState.IsValid)
        {
            if (professor.Id > 0)
            {
                await _repository.Atualizar(professor);
                return RedirectToAction("Listar");
            }
            await _repository.Adicionar(professor);
            return RedirectToAction("Listar");
        }
        
        return View("Adicionar", professor);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Atualizar(int id)
    {
        var professor = await _repository.GetById(id);
        return View("Adicionar", professor);    
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Remover(int id)
    {
        await _repository.Remover(id);
        return RedirectToAction("Listar");
    }
    
    public async Task<IActionResult> Listar()
    {
        var professor =  await _repository.Listar();
        return View(professor);
    }
}

Views/Aluno/Adicionar.cshtml
@model Aluno
@{
    if (Model.Id > 0)
    {
        ViewData["Title"] = "Editar Aluno";
    }
    else
    {
        ViewData["Title"] = "Adicionar Aluno";
    }
}

<h2>
    @if (Model.Id > 0)
    {
        <text>Editar Aluno</text>
    }
    else
    {
        <text>Adicionar Aluno</text>
    }
</h2>
<form asp-action="Adicionar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Nome" for="exampleInputEmail1" class="form-label">Nome</label>
        <input asp-for="Nome" type="text" class="form-control" id="exampleInputEmail1">
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Nome)</span>
    </div>
    <div class="mb-3">
        <label asp-for="RA" class="form-label">RA</label>
        <input asp-for="RA" type="number" class="form-control">
        <span class="text-danger">@Html.ValidationMessageFor(model => model.RA)</span>
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" type="email" class="form-control">
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Email)</span>
    </div>
    <button type="submit" class="btn btn-primary">Confirmar</button>
</form>

Views/Aluno/Listar.cshtml
@model List<Aluno>

<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">RA</th>
        <th scope="col">Email</th>
        <th scope="col">Editar</th>
        <th scope="col">Remover</th>
    </tr>
    </thead>
    @foreach (var aluno in Model)
    {
        <tr>
            <td>@aluno.Id</td>
            <td>@aluno.Nome</td>
            <td>@aluno.RA</td>
            <td>@aluno.Email</td>
            <td>
                <form asp-action="Atualizar" asp-route-id="@aluno.Id" method="post" class="d-inline">
                    <button type="submit" class="btn btn-sm btn-warning">Editar</button>
                </form>
            </td>
            <td>
                <form asp-action="Remover" asp-route-id="@aluno.Id" method="post" onsubmit="return confirm('Certeza que deseja excluir @aluno.Nome?')" class="d-inline">
                    <input type="hidden" name="id" value="@aluno.Id" />
                    <button type="submit" class="btn btn-sm btn-danger">Remover</button>
                </form>
            </td>
        </tr>
    }
</table>

<div class="text-center">
    <a href="@Url.Action("Adicionar", "Aluno")" class="btn btn-primary">Cadastrar Aluno</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Professor/Adicionar.cshtml
@model Professor
@{
    if (Model.Id > 0)
    {
        ViewData["Title"] = "Editar Pessoa";
    }
    else
    {
        ViewData["Title"] = "Criar Pessoa";
    }
}

<h2>
    @if (Model.Id > 0)
    {
        <text>Editar Professor</text>
    }
    else
    {
        <text>Adicionar Professor</text>
    }
</h2>
<form asp-action="Adicionar" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Nome" for="exampleInputEmail1" class="form-label">Nome</label>
        <input asp-for="Nome" type="text" class="form-control" id="exampleInputEmail1">
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Nome)</span>
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label">Email</label>
        <input asp-for="Email" type="email" class="form-control">
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Email)</span>
    </div>
    <div class="mb-3">
        <label asp-for="Telefone" class="form-label">Telefone</label>
        <input asp-for="Telefone" type="number" class="form-control">
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Telefone)</span>
    </div>
    <div class="mb-3">
        <label asp-for="Disciplina" class="form-label">Disciplina</label>
        <input asp-for="Disciplina" type="text" class="form-control">
        <span class="text-danger">@Html.ValidationMessageFor(model => model.Disciplina)</span>
    </div>
    <button type="submit" class="btn btn-primary">Confirmar</button>
</form>

Views/Professor/Listar.cshtml
@model List<Professor>

<table class="table">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Telefone</th>
        <th scope="col">Disciplina</th>
        <th scope="col">Editar</th>
        <th scope="col">Remover</th>
    </tr>
    </thead>
    @foreach (var professor in Model)
    {
        <tr>
            <td>@professor.Id</td>
            <td>@professor.Nome</td>
            <td>@professor.Email</td>
            <td>@professor.Telefone</td>
            <td>@professor.Disciplina</td>
            <td>
                <form asp-action="Atualizar" asp-route-id="@professor.Id" method="post" class="d-inline">
                    <button type="submit" class="btn btn-sm btn-warning">Editar</button>
                </form>
            </td>
            <td>
                <form asp-action="Remover" asp-route-id="@professor.Id" method="post" onsubmit="return confirm('Certeza que deseja excluir @professor.Nome?')" class="d-inline">
                    <input type="hidden" name="id" value="@professor.Id" />
                    <button type="submit" class="btn btn-sm btn-danger">Remover</button>
                </form>
            </td>
        </tr>
    }
</table>

<div class="text-center">
    <a href="@Url.Action("Adicionar", "Professor")" class="btn btn-primary">Cadastrar Professor</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SistemaEscolar</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SistemaEscolar.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaEscolar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Professor" asp-action="Listar">Professores</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Listar">Alunos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - SistemaEscolar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>